
package frc.cotc.autos;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

// If these imports cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj DepotLeft = new ChoreoTraj(
	    "DepotLeft",
	    OptionalInt.empty(),
	    2.87394,
	    new Pose2d(3.729, 5.964, Rotation2d.fromRadians(3.142)),
	    new Pose2d(2.99, 5.285, Rotation2d.fromRadians(-2.308))
	);
	public static final ChoreoTraj DepotLeft$0 = new ChoreoTraj(
	    "DepotLeft",
	    OptionalInt.of(0),
	    1.65395,
	    new Pose2d(3.729, 5.964, Rotation2d.fromRadians(3.142)),
	    new Pose2d(0.591, 5.964, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj DepotLeft$1 = new ChoreoTraj(
	    "DepotLeft",
	    OptionalInt.of(1),
	    1.2199900000000001,
	    new Pose2d(0.591, 5.964, Rotation2d.fromRadians(3.142)),
	    new Pose2d(2.99, 5.285, Rotation2d.fromRadians(-2.308))
	);
	public static final ChoreoTraj OutpostRight = new ChoreoTraj(
	    "OutpostRight",
	    OptionalInt.empty(),
	    3.26868,
	    new Pose2d(3.675, 1.738, Rotation2d.fromRadians(0)),
	    new Pose2d(2.861, 2.966, Rotation2d.fromRadians(-1.109))
	);
	public static final ChoreoTraj OutpostRight$0 = new ChoreoTraj(
	    "OutpostRight",
	    OptionalInt.of(0),
	    1.84601,
	    new Pose2d(3.675, 1.738, Rotation2d.fromRadians(0)),
	    new Pose2d(0.615, 0.658, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj OutpostRight$1 = new ChoreoTraj(
	    "OutpostRight",
	    OptionalInt.of(1),
	    1.4226699999999999,
	    new Pose2d(0.615, 0.658, Rotation2d.fromRadians(3.142)),
	    new Pose2d(2.861, 2.966, Rotation2d.fromRadians(-1.109))
	);
	public static final ChoreoTraj Center = new ChoreoTraj(
	    "Center",
	    OptionalInt.empty(),
	    0.83295,
	    new Pose2d(3.668, 4.019, Rotation2d.fromRadians(0)),
	    new Pose2d(2.567, 4.002, Rotation2d.fromRadians(-1.571))
	);

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("DepotLeft", DepotLeft),
		Map.entry("DepotLeft$0", DepotLeft$0),
		Map.entry("DepotLeft$1", DepotLeft$1),
		Map.entry("OutpostRight", OutpostRight),
		Map.entry("OutpostRight$0", OutpostRight$0),
		Map.entry("OutpostRight$1", OutpostRight$1),
		Map.entry("Center", Center)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
