// spotless:off
package frc.cotc.autos;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;
// If the 2 imports above cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj FarLeftDepot = new ChoreoTraj(
        "FarLeftDepot",
        OptionalInt.empty(),
        3.17937,
        new Pose2d(3.68, 7.589, Rotation2d.fromRadians(0)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarLeftDepot$0 = new ChoreoTraj(
        "FarLeftDepot",
        OptionalInt.of(0),
        1.34019,
        new Pose2d(3.68, 7.589, Rotation2d.fromRadians(0)),
        new Pose2d(1.25, 5.9843, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarLeftDepot$1 = new ChoreoTraj(
        "FarLeftDepot",
        OptionalInt.of(1),
        0.72264,
        new Pose2d(1.25, 5.9843, Rotation2d.fromRadians(3.14159)),
        new Pose2d(0.59855, 5.9843, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarLeftDepot$2 = new ChoreoTraj(
        "FarLeftDepot",
        OptionalInt.of(2),
        1.11654,
        new Pose2d(0.59855, 5.9843, Rotation2d.fromRadians(3.14159)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    public static final ChoreoTraj FarRightOutpost = new ChoreoTraj(
        "FarRightOutpost",
        OptionalInt.empty(),
        3.11264,
        new Pose2d(3.68, 0.48, Rotation2d.fromRadians(0)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarRightOutpost$0 = new ChoreoTraj(
        "FarRightOutpost",
        OptionalInt.of(0),
        1.79121,
        new Pose2d(3.68, 0.48, Rotation2d.fromRadians(0)),
        new Pose2d(0.56, 0.68, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarRightOutpost$1 = new ChoreoTraj(
        "FarRightOutpost",
        OptionalInt.of(1),
        1.3214299999999999,
        new Pose2d(0.56, 0.68, Rotation2d.fromRadians(3.14159)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    public static final ChoreoTraj LeftBumpClose = new ChoreoTraj(
        "LeftBumpClose",
        OptionalInt.empty(),
        5.27538,
        new Pose2d(3.68, 5.869, Rotation2d.fromRadians(0)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpClose$0 = new ChoreoTraj(
        "LeftBumpClose",
        OptionalInt.of(0),
        1.68601,
        new Pose2d(3.68, 5.869, Rotation2d.fromRadians(0)),
        new Pose2d(6.2, 6.069, Rotation2d.fromRadians(-1.5708))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpClose$1 = new ChoreoTraj(
        "LeftBumpClose",
        OptionalInt.of(1),
        1.13931,
        new Pose2d(6.2, 6.069, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(6.2, 4.569, Rotation2d.fromRadians(-1.5708))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpClose$2 = new ChoreoTraj(
        "LeftBumpClose",
        OptionalInt.of(2),
        2.45006,
        new Pose2d(6.2, 4.569, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    public static final ChoreoTraj LeftBumpFar = new ChoreoTraj(
        "LeftBumpFar",
        OptionalInt.empty(),
        6.6829,
        new Pose2d(3.68, 5.569, Rotation2d.fromRadians(0)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpFar$0 = new ChoreoTraj(
        "LeftBumpFar",
        OptionalInt.of(0),
        2.50994,
        new Pose2d(3.68, 5.569, Rotation2d.fromRadians(0)),
        new Pose2d(8.75, 7.069, Rotation2d.fromRadians(-1.91986))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpFar$1 = new ChoreoTraj(
        "LeftBumpFar",
        OptionalInt.of(1),
        1.3541700000000003,
        new Pose2d(8.75, 7.069, Rotation2d.fromRadians(-1.91986)),
        new Pose2d(8.75, 5.069, Rotation2d.fromRadians(-1.91986))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpFar$2 = new ChoreoTraj(
        "LeftBumpFar",
        OptionalInt.of(2),
        2.81879,
        new Pose2d(8.75, 5.069, Rotation2d.fromRadians(-1.91986)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    public static final ChoreoTraj LeftBumpFarAcross = new ChoreoTraj(
        "LeftBumpFarAcross",
        OptionalInt.empty(),
        7.18577,
        new Pose2d(3.68, 5.569, Rotation2d.fromRadians(0)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpFarAcross$0 = new ChoreoTraj(
        "LeftBumpFarAcross",
        OptionalInt.of(0),
        2.54518,
        new Pose2d(3.68, 5.569, Rotation2d.fromRadians(0)),
        new Pose2d(8.75, 7.069, Rotation2d.fromRadians(-1.91986))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpFarAcross$1 = new ChoreoTraj(
        "LeftBumpFarAcross",
        OptionalInt.of(1),
        1.6562199999999994,
        new Pose2d(8.75, 7.069, Rotation2d.fromRadians(-1.91986)),
        new Pose2d(8.75, 1.369, Rotation2d.fromRadians(-1.91986))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpFarAcross$2 = new ChoreoTraj(
        "LeftBumpFarAcross",
        OptionalInt.of(2),
        2.98437,
        new Pose2d(8.75, 1.369, Rotation2d.fromRadians(-1.91986)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    public static final ChoreoTraj LeftBumpFarAcrossClose = new ChoreoTraj(
        "LeftBumpFarAcrossClose",
        OptionalInt.empty(),
        13.05921,
        new Pose2d(3.68, 5.569, Rotation2d.fromRadians(0)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpFarAcrossClose$0 = new ChoreoTraj(
        "LeftBumpFarAcrossClose",
        OptionalInt.of(0),
        2.54518,
        new Pose2d(3.68, 5.569, Rotation2d.fromRadians(0)),
        new Pose2d(8.75, 7.069, Rotation2d.fromRadians(-1.91986))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpFarAcrossClose$1 = new ChoreoTraj(
        "LeftBumpFarAcrossClose",
        OptionalInt.of(1),
        1.6562199999999994,
        new Pose2d(8.75, 7.069, Rotation2d.fromRadians(-1.91986)),
        new Pose2d(8.75, 1.369, Rotation2d.fromRadians(-1.91986))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpFarAcrossClose$2 = new ChoreoTraj(
        "LeftBumpFarAcrossClose",
        OptionalInt.of(2),
        2.98437,
        new Pose2d(8.75, 1.369, Rotation2d.fromRadians(-1.91986)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpFarAcrossClose$3 = new ChoreoTraj(
        "LeftBumpFarAcrossClose",
        OptionalInt.of(3),
        2.2769600000000008,
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265)),
        new Pose2d(6.2, 2, Rotation2d.fromRadians(1.5708))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpFarAcrossClose$4 = new ChoreoTraj(
        "LeftBumpFarAcrossClose",
        OptionalInt.of(4),
        1.1391399999999994,
        new Pose2d(6.2, 2, Rotation2d.fromRadians(1.5708)),
        new Pose2d(6.2, 3.5, Rotation2d.fromRadians(1.5708))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpFarAcrossClose$5 = new ChoreoTraj(
        "LeftBumpFarAcrossClose",
        OptionalInt.of(5),
        2.4573400000000003,
        new Pose2d(6.2, 3.5, Rotation2d.fromRadians(1.5708)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    public static final ChoreoTraj LeftBumpFarAcrossOutpost = new ChoreoTraj(
        "LeftBumpFarAcrossOutpost",
        OptionalInt.empty(),
        10.00054,
        new Pose2d(3.68, 5.569, Rotation2d.fromRadians(0)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpFarAcrossOutpost$0 = new ChoreoTraj(
        "LeftBumpFarAcrossOutpost",
        OptionalInt.of(0),
        2.54518,
        new Pose2d(3.68, 5.569, Rotation2d.fromRadians(0)),
        new Pose2d(8.75, 7.069, Rotation2d.fromRadians(-1.91986))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpFarAcrossOutpost$1 = new ChoreoTraj(
        "LeftBumpFarAcrossOutpost",
        OptionalInt.of(1),
        1.6562199999999994,
        new Pose2d(8.75, 7.069, Rotation2d.fromRadians(-1.91986)),
        new Pose2d(8.75, 1.369, Rotation2d.fromRadians(-1.91986))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpFarAcrossOutpost$2 = new ChoreoTraj(
        "LeftBumpFarAcrossOutpost",
        OptionalInt.of(2),
        2.98437,
        new Pose2d(8.75, 1.369, Rotation2d.fromRadians(-1.91986)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpFarAcrossOutpost$3 = new ChoreoTraj(
        "LeftBumpFarAcrossOutpost",
        OptionalInt.of(3),
        1.4933499999999995,
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265)),
        new Pose2d(0.56, 0.68, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpFarAcrossOutpost$4 = new ChoreoTraj(
        "LeftBumpFarAcrossOutpost",
        OptionalInt.of(4),
        1.3214200000000016,
        new Pose2d(0.56, 0.68, Rotation2d.fromRadians(3.14159)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    public static final ChoreoTraj LeftBumpFarClose = new ChoreoTraj(
        "LeftBumpFarClose",
        OptionalInt.empty(),
        12.62082,
        new Pose2d(3.68, 5.569, Rotation2d.fromRadians(0)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpFarClose$0 = new ChoreoTraj(
        "LeftBumpFarClose",
        OptionalInt.of(0),
        2.50994,
        new Pose2d(3.68, 5.569, Rotation2d.fromRadians(0)),
        new Pose2d(8.75, 7.069, Rotation2d.fromRadians(-1.91986))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpFarClose$1 = new ChoreoTraj(
        "LeftBumpFarClose",
        OptionalInt.of(1),
        1.3541700000000003,
        new Pose2d(8.75, 7.069, Rotation2d.fromRadians(-1.91986)),
        new Pose2d(8.75, 5.069, Rotation2d.fromRadians(-1.91986))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpFarClose$2 = new ChoreoTraj(
        "LeftBumpFarClose",
        OptionalInt.of(2),
        2.81879,
        new Pose2d(8.75, 5.069, Rotation2d.fromRadians(-1.91986)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpFarClose$3 = new ChoreoTraj(
        "LeftBumpFarClose",
        OptionalInt.of(3),
        2.349169999999999,
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674)),
        new Pose2d(6.2, 6.069, Rotation2d.fromRadians(-1.5708))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpFarClose$4 = new ChoreoTraj(
        "LeftBumpFarClose",
        OptionalInt.of(4),
        1.1386000000000003,
        new Pose2d(6.2, 6.069, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(6.2, 4.569, Rotation2d.fromRadians(-1.5708))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpFarClose$5 = new ChoreoTraj(
        "LeftBumpFarClose",
        OptionalInt.of(5),
        2.4501500000000007,
        new Pose2d(6.2, 4.569, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    public static final ChoreoTraj LeftBumpFarDepot = new ChoreoTraj(
        "LeftBumpFarDepot",
        OptionalInt.empty(),
        9.32921,
        new Pose2d(3.68, 5.569, Rotation2d.fromRadians(0)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpFarDepot$0 = new ChoreoTraj(
        "LeftBumpFarDepot",
        OptionalInt.of(0),
        2.50994,
        new Pose2d(3.68, 5.569, Rotation2d.fromRadians(0)),
        new Pose2d(8.75, 7.069, Rotation2d.fromRadians(-1.91986))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpFarDepot$1 = new ChoreoTraj(
        "LeftBumpFarDepot",
        OptionalInt.of(1),
        1.3541700000000003,
        new Pose2d(8.75, 7.069, Rotation2d.fromRadians(-1.91986)),
        new Pose2d(8.75, 5.069, Rotation2d.fromRadians(-1.91986))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpFarDepot$2 = new ChoreoTraj(
        "LeftBumpFarDepot",
        OptionalInt.of(2),
        2.81879,
        new Pose2d(8.75, 5.069, Rotation2d.fromRadians(-1.91986)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpFarDepot$3 = new ChoreoTraj(
        "LeftBumpFarDepot",
        OptionalInt.of(3),
        0.8273399999999995,
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674)),
        new Pose2d(1.25, 5.9843, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpFarDepot$4 = new ChoreoTraj(
        "LeftBumpFarDepot",
        OptionalInt.of(4),
        0.7227700000000006,
        new Pose2d(1.25, 5.9843, Rotation2d.fromRadians(3.14159)),
        new Pose2d(0.59855, 5.9843, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpFarDepot$5 = new ChoreoTraj(
        "LeftBumpFarDepot",
        OptionalInt.of(5),
        1.0961999999999996,
        new Pose2d(0.59855, 5.9843, Rotation2d.fromRadians(3.14159)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    public static final ChoreoTraj LeftBumpMid = new ChoreoTraj(
        "LeftBumpMid",
        OptionalInt.empty(),
        6.53179,
        new Pose2d(3.68, 5.569, Rotation2d.fromRadians(0)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpMid$0 = new ChoreoTraj(
        "LeftBumpMid",
        OptionalInt.of(0),
        2.36267,
        new Pose2d(3.68, 5.569, Rotation2d.fromRadians(0)),
        new Pose2d(8.05, 7.069, Rotation2d.fromRadians(-2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpMid$1 = new ChoreoTraj(
        "LeftBumpMid",
        OptionalInt.of(1),
        1.5066000000000002,
        new Pose2d(8.05, 7.069, Rotation2d.fromRadians(-2.0944)),
        new Pose2d(8.05, 4.869, Rotation2d.fromRadians(-2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpMid$2 = new ChoreoTraj(
        "LeftBumpMid",
        OptionalInt.of(2),
        2.6625199999999998,
        new Pose2d(8.05, 4.869, Rotation2d.fromRadians(-2.0944)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    public static final ChoreoTraj LeftBumpMidClose = new ChoreoTraj(
        "LeftBumpMidClose",
        OptionalInt.empty(),
        12.47112,
        new Pose2d(3.68, 5.569, Rotation2d.fromRadians(0)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpMidClose$0 = new ChoreoTraj(
        "LeftBumpMidClose",
        OptionalInt.of(0),
        2.36639,
        new Pose2d(3.68, 5.569, Rotation2d.fromRadians(0)),
        new Pose2d(8.05, 7.069, Rotation2d.fromRadians(-2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpMidClose$1 = new ChoreoTraj(
        "LeftBumpMidClose",
        OptionalInt.of(1),
        1.5073400000000001,
        new Pose2d(8.05, 7.069, Rotation2d.fromRadians(-2.0944)),
        new Pose2d(8.05, 4.869, Rotation2d.fromRadians(-2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpMidClose$2 = new ChoreoTraj(
        "LeftBumpMidClose",
        OptionalInt.of(2),
        2.65946,
        new Pose2d(8.05, 4.869, Rotation2d.fromRadians(-2.0944)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpMidClose$3 = new ChoreoTraj(
        "LeftBumpMidClose",
        OptionalInt.of(3),
        2.3491799999999996,
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674)),
        new Pose2d(6.2, 6.069, Rotation2d.fromRadians(-1.5708))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpMidClose$4 = new ChoreoTraj(
        "LeftBumpMidClose",
        OptionalInt.of(4),
        1.1385900000000007,
        new Pose2d(6.2, 6.069, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(6.2, 4.569, Rotation2d.fromRadians(-1.5708))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpMidClose$5 = new ChoreoTraj(
        "LeftBumpMidClose",
        OptionalInt.of(5),
        2.4501600000000003,
        new Pose2d(6.2, 4.569, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    public static final ChoreoTraj LeftBumpMidDepot = new ChoreoTraj(
        "LeftBumpMidDepot",
        OptionalInt.empty(),
        9.17811,
        new Pose2d(3.68, 5.569, Rotation2d.fromRadians(0)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpMidDepot$0 = new ChoreoTraj(
        "LeftBumpMidDepot",
        OptionalInt.of(0),
        2.36267,
        new Pose2d(3.68, 5.569, Rotation2d.fromRadians(0)),
        new Pose2d(8.05, 7.069, Rotation2d.fromRadians(-2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpMidDepot$1 = new ChoreoTraj(
        "LeftBumpMidDepot",
        OptionalInt.of(1),
        1.5066000000000002,
        new Pose2d(8.05, 7.069, Rotation2d.fromRadians(-2.0944)),
        new Pose2d(8.05, 4.869, Rotation2d.fromRadians(-2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpMidDepot$2 = new ChoreoTraj(
        "LeftBumpMidDepot",
        OptionalInt.of(2),
        2.6625199999999998,
        new Pose2d(8.05, 4.869, Rotation2d.fromRadians(-2.0944)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpMidDepot$3 = new ChoreoTraj(
        "LeftBumpMidDepot",
        OptionalInt.of(3),
        0.82735,
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674)),
        new Pose2d(1.25, 5.9843, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpMidDepot$4 = new ChoreoTraj(
        "LeftBumpMidDepot",
        OptionalInt.of(4),
        0.7227700000000006,
        new Pose2d(1.25, 5.9843, Rotation2d.fromRadians(3.14159)),
        new Pose2d(0.59855, 5.9843, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftBumpMidDepot$5 = new ChoreoTraj(
        "LeftBumpMidDepot",
        OptionalInt.of(5),
        1.0961999999999996,
        new Pose2d(0.59855, 5.9843, Rotation2d.fromRadians(3.14159)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    public static final ChoreoTraj RightBumpClose = new ChoreoTraj(
        "RightBumpClose",
        OptionalInt.empty(),
        5.28263,
        new Pose2d(3.68, 2.2, Rotation2d.fromRadians(0)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpClose$0 = new ChoreoTraj(
        "RightBumpClose",
        OptionalInt.of(0),
        1.68552,
        new Pose2d(3.68, 2.2, Rotation2d.fromRadians(0)),
        new Pose2d(6.2, 2, Rotation2d.fromRadians(1.5708))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpClose$1 = new ChoreoTraj(
        "RightBumpClose",
        OptionalInt.of(1),
        1.13986,
        new Pose2d(6.2, 2, Rotation2d.fromRadians(1.5708)),
        new Pose2d(6.2, 3.5, Rotation2d.fromRadians(1.5708))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpClose$2 = new ChoreoTraj(
        "RightBumpClose",
        OptionalInt.of(2),
        2.45725,
        new Pose2d(6.2, 3.5, Rotation2d.fromRadians(1.5708)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    public static final ChoreoTraj RightBumpFar = new ChoreoTraj(
        "RightBumpFar",
        OptionalInt.empty(),
        6.76325,
        new Pose2d(3.68, 2.5, Rotation2d.fromRadians(0)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpFar$0 = new ChoreoTraj(
        "RightBumpFar",
        OptionalInt.of(0),
        2.51588,
        new Pose2d(3.68, 2.5, Rotation2d.fromRadians(0)),
        new Pose2d(8.75, 1, Rotation2d.fromRadians(2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpFar$1 = new ChoreoTraj(
        "RightBumpFar",
        OptionalInt.of(1),
        1.3538799999999998,
        new Pose2d(8.75, 1, Rotation2d.fromRadians(2.0944)),
        new Pose2d(8.75, 3, Rotation2d.fromRadians(2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpFar$2 = new ChoreoTraj(
        "RightBumpFar",
        OptionalInt.of(2),
        2.8934900000000003,
        new Pose2d(8.75, 3, Rotation2d.fromRadians(2.0944)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    public static final ChoreoTraj RightBumpFarAcross = new ChoreoTraj(
        "RightBumpFarAcross",
        OptionalInt.empty(),
        7.12932,
        new Pose2d(3.68, 2.5, Rotation2d.fromRadians(0)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpFarAcross$0 = new ChoreoTraj(
        "RightBumpFarAcross",
        OptionalInt.of(0),
        2.55306,
        new Pose2d(3.68, 2.5, Rotation2d.fromRadians(0)),
        new Pose2d(8.75, 1, Rotation2d.fromRadians(2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpFarAcross$1 = new ChoreoTraj(
        "RightBumpFarAcross",
        OptionalInt.of(1),
        1.6623699999999997,
        new Pose2d(8.75, 1, Rotation2d.fromRadians(2.0944)),
        new Pose2d(8.75, 6.7, Rotation2d.fromRadians(2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpFarAcross$2 = new ChoreoTraj(
        "RightBumpFarAcross",
        OptionalInt.of(2),
        2.9138900000000003,
        new Pose2d(8.75, 6.7, Rotation2d.fromRadians(2.0944)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    public static final ChoreoTraj RightBumpFarAcrossClose = new ChoreoTraj(
        "RightBumpFarAcrossClose",
        OptionalInt.empty(),
        13.06724,
        new Pose2d(3.68, 2.5, Rotation2d.fromRadians(0)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpFarAcrossClose$0 = new ChoreoTraj(
        "RightBumpFarAcrossClose",
        OptionalInt.of(0),
        2.55306,
        new Pose2d(3.68, 2.5, Rotation2d.fromRadians(0)),
        new Pose2d(8.75, 1, Rotation2d.fromRadians(2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpFarAcrossClose$1 = new ChoreoTraj(
        "RightBumpFarAcrossClose",
        OptionalInt.of(1),
        1.6623699999999997,
        new Pose2d(8.75, 1, Rotation2d.fromRadians(2.0944)),
        new Pose2d(8.75, 6.7, Rotation2d.fromRadians(2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpFarAcrossClose$2 = new ChoreoTraj(
        "RightBumpFarAcrossClose",
        OptionalInt.of(2),
        2.9138900000000003,
        new Pose2d(8.75, 6.7, Rotation2d.fromRadians(2.0944)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpFarAcrossClose$3 = new ChoreoTraj(
        "RightBumpFarAcrossClose",
        OptionalInt.of(3),
        2.349170000000001,
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674)),
        new Pose2d(6.2, 6.069, Rotation2d.fromRadians(-1.5708))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpFarAcrossClose$4 = new ChoreoTraj(
        "RightBumpFarAcrossClose",
        OptionalInt.of(4),
        1.1385999999999985,
        new Pose2d(6.2, 6.069, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(6.2, 4.569, Rotation2d.fromRadians(-1.5708))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpFarAcrossClose$5 = new ChoreoTraj(
        "RightBumpFarAcrossClose",
        OptionalInt.of(5),
        2.4501500000000007,
        new Pose2d(6.2, 4.569, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    public static final ChoreoTraj RightBumpFarAcrossDepot = new ChoreoTraj(
        "RightBumpFarAcrossDepot",
        OptionalInt.empty(),
        9.77563,
        new Pose2d(3.68, 2.5, Rotation2d.fromRadians(0)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpFarAcrossDepot$0 = new ChoreoTraj(
        "RightBumpFarAcrossDepot",
        OptionalInt.of(0),
        2.55306,
        new Pose2d(3.68, 2.5, Rotation2d.fromRadians(0)),
        new Pose2d(8.75, 1, Rotation2d.fromRadians(2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpFarAcrossDepot$1 = new ChoreoTraj(
        "RightBumpFarAcrossDepot",
        OptionalInt.of(1),
        1.6623699999999997,
        new Pose2d(8.75, 1, Rotation2d.fromRadians(2.0944)),
        new Pose2d(8.75, 6.7, Rotation2d.fromRadians(2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpFarAcrossDepot$2 = new ChoreoTraj(
        "RightBumpFarAcrossDepot",
        OptionalInt.of(2),
        2.9138900000000003,
        new Pose2d(8.75, 6.7, Rotation2d.fromRadians(2.0944)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpFarAcrossDepot$3 = new ChoreoTraj(
        "RightBumpFarAcrossDepot",
        OptionalInt.of(3),
        0.8273400000000004,
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674)),
        new Pose2d(1.25, 5.9843, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpFarAcrossDepot$4 = new ChoreoTraj(
        "RightBumpFarAcrossDepot",
        OptionalInt.of(4),
        0.7227699999999997,
        new Pose2d(1.25, 5.9843, Rotation2d.fromRadians(3.14159)),
        new Pose2d(0.59855, 5.9843, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpFarAcrossDepot$5 = new ChoreoTraj(
        "RightBumpFarAcrossDepot",
        OptionalInt.of(5),
        1.0961999999999996,
        new Pose2d(0.59855, 5.9843, Rotation2d.fromRadians(3.14159)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    public static final ChoreoTraj RightBumpFarClose = new ChoreoTraj(
        "RightBumpFarClose",
        OptionalInt.empty(),
        12.4537,
        new Pose2d(3.68, 2.5, Rotation2d.fromRadians(0)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpFarClose$0 = new ChoreoTraj(
        "RightBumpFarClose",
        OptionalInt.of(0),
        2.51588,
        new Pose2d(3.68, 2.5, Rotation2d.fromRadians(0)),
        new Pose2d(8.75, 1, Rotation2d.fromRadians(2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpFarClose$1 = new ChoreoTraj(
        "RightBumpFarClose",
        OptionalInt.of(1),
        1.3538799999999998,
        new Pose2d(8.75, 1, Rotation2d.fromRadians(2.0944)),
        new Pose2d(8.75, 3, Rotation2d.fromRadians(2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpFarClose$2 = new ChoreoTraj(
        "RightBumpFarClose",
        OptionalInt.of(2),
        2.8934900000000003,
        new Pose2d(8.75, 3, Rotation2d.fromRadians(2.0944)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpFarClose$3 = new ChoreoTraj(
        "RightBumpFarClose",
        OptionalInt.of(3),
        2.27851,
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265)),
        new Pose2d(6.2, 2, Rotation2d.fromRadians(1.5708))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpFarClose$4 = new ChoreoTraj(
        "RightBumpFarClose",
        OptionalInt.of(4),
        0.9612499999999997,
        new Pose2d(6.2, 2, Rotation2d.fromRadians(1.5708)),
        new Pose2d(6.2, 3.5, Rotation2d.fromRadians(1.5708))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpFarClose$5 = new ChoreoTraj(
        "RightBumpFarClose",
        OptionalInt.of(5),
        2.45069,
        new Pose2d(6.2, 3.5, Rotation2d.fromRadians(1.5708)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    public static final ChoreoTraj RightBumpFarOutpost = new ChoreoTraj(
        "RightBumpFarOutpost",
        OptionalInt.empty(),
        9.76296,
        new Pose2d(3.68, 2.5, Rotation2d.fromRadians(0)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpFarOutpost$0 = new ChoreoTraj(
        "RightBumpFarOutpost",
        OptionalInt.of(0),
        2.51588,
        new Pose2d(3.68, 2.5, Rotation2d.fromRadians(0)),
        new Pose2d(8.75, 1, Rotation2d.fromRadians(2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpFarOutpost$1 = new ChoreoTraj(
        "RightBumpFarOutpost",
        OptionalInt.of(1),
        1.3538799999999998,
        new Pose2d(8.75, 1, Rotation2d.fromRadians(2.0944)),
        new Pose2d(8.75, 3, Rotation2d.fromRadians(2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpFarOutpost$2 = new ChoreoTraj(
        "RightBumpFarOutpost",
        OptionalInt.of(2),
        2.8934900000000003,
        new Pose2d(8.75, 3, Rotation2d.fromRadians(2.0944)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpFarOutpost$3 = new ChoreoTraj(
        "RightBumpFarOutpost",
        OptionalInt.of(3),
        1.67828,
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265)),
        new Pose2d(0.56, 0.68, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpFarOutpost$4 = new ChoreoTraj(
        "RightBumpFarOutpost",
        OptionalInt.of(4),
        1.3214299999999994,
        new Pose2d(0.56, 0.68, Rotation2d.fromRadians(3.14159)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    public static final ChoreoTraj RightBumpMid = new ChoreoTraj(
        "RightBumpMid",
        OptionalInt.empty(),
        6.6118,
        new Pose2d(3.68, 2.5, Rotation2d.fromRadians(0)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpMid$0 = new ChoreoTraj(
        "RightBumpMid",
        OptionalInt.of(0),
        2.36306,
        new Pose2d(3.68, 2.5, Rotation2d.fromRadians(0)),
        new Pose2d(8.05, 1, Rotation2d.fromRadians(2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpMid$1 = new ChoreoTraj(
        "RightBumpMid",
        OptionalInt.of(1),
        1.4953600000000002,
        new Pose2d(8.05, 1, Rotation2d.fromRadians(2.0944)),
        new Pose2d(8.05, 3.2, Rotation2d.fromRadians(2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpMid$2 = new ChoreoTraj(
        "RightBumpMid",
        OptionalInt.of(2),
        2.7533799999999995,
        new Pose2d(8.05, 3.2, Rotation2d.fromRadians(2.0944)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    public static final ChoreoTraj RightBumpMidClose = new ChoreoTraj(
        "RightBumpMidClose",
        OptionalInt.empty(),
        12.48524,
        new Pose2d(3.68, 2.5, Rotation2d.fromRadians(0)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpMidClose$0 = new ChoreoTraj(
        "RightBumpMidClose",
        OptionalInt.of(0),
        2.36306,
        new Pose2d(3.68, 2.5, Rotation2d.fromRadians(0)),
        new Pose2d(8.05, 1, Rotation2d.fromRadians(2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpMidClose$1 = new ChoreoTraj(
        "RightBumpMidClose",
        OptionalInt.of(1),
        1.4953600000000002,
        new Pose2d(8.05, 1, Rotation2d.fromRadians(2.0944)),
        new Pose2d(8.05, 3.2, Rotation2d.fromRadians(2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpMidClose$2 = new ChoreoTraj(
        "RightBumpMidClose",
        OptionalInt.of(2),
        2.7533799999999995,
        new Pose2d(8.05, 3.2, Rotation2d.fromRadians(2.0944)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpMidClose$3 = new ChoreoTraj(
        "RightBumpMidClose",
        OptionalInt.of(3),
        2.27696,
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265)),
        new Pose2d(6.2, 2, Rotation2d.fromRadians(1.5708))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpMidClose$4 = new ChoreoTraj(
        "RightBumpMidClose",
        OptionalInt.of(4),
        1.1391400000000012,
        new Pose2d(6.2, 2, Rotation2d.fromRadians(1.5708)),
        new Pose2d(6.2, 3.5, Rotation2d.fromRadians(1.5708))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpMidClose$5 = new ChoreoTraj(
        "RightBumpMidClose",
        OptionalInt.of(5),
        2.4573399999999985,
        new Pose2d(6.2, 3.5, Rotation2d.fromRadians(1.5708)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    public static final ChoreoTraj RightBumpMidOutpost = new ChoreoTraj(
        "RightBumpMidOutpost",
        OptionalInt.empty(),
        9.61151,
        new Pose2d(3.68, 2.5, Rotation2d.fromRadians(0)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpMidOutpost$0 = new ChoreoTraj(
        "RightBumpMidOutpost",
        OptionalInt.of(0),
        2.36306,
        new Pose2d(3.68, 2.5, Rotation2d.fromRadians(0)),
        new Pose2d(8.05, 1, Rotation2d.fromRadians(2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpMidOutpost$1 = new ChoreoTraj(
        "RightBumpMidOutpost",
        OptionalInt.of(1),
        1.4953600000000002,
        new Pose2d(8.05, 1, Rotation2d.fromRadians(2.0944)),
        new Pose2d(8.05, 3.2, Rotation2d.fromRadians(2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpMidOutpost$2 = new ChoreoTraj(
        "RightBumpMidOutpost",
        OptionalInt.of(2),
        2.7533799999999995,
        new Pose2d(8.05, 3.2, Rotation2d.fromRadians(2.0944)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpMidOutpost$3 = new ChoreoTraj(
        "RightBumpMidOutpost",
        OptionalInt.of(3),
        1.67828,
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265)),
        new Pose2d(0.56, 0.68, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightBumpMidOutpost$4 = new ChoreoTraj(
        "RightBumpMidOutpost",
        OptionalInt.of(4),
        1.3214300000000012,
        new Pose2d(0.56, 0.68, Rotation2d.fromRadians(3.14159)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    public static final ChoreoTraj Warmup = new ChoreoTraj(
        "Warmup",
        OptionalInt.empty(),
        1.05327,
        new Pose2d(0, 0, Rotation2d.fromRadians(0)),
        new Pose2d(1, 1, Rotation2d.fromRadians(3.14159))
    );
    public static final ChoreoTraj Center = new ChoreoTraj(
        "Center",
        OptionalInt.empty(),
        1.02739,
        new Pose2d(3.68, 4.0345, Rotation2d.fromRadians(0)),
        new Pose2d(2, 3.8694, Rotation2d.fromRadians(-1.5708))
    );
    public static final ChoreoTraj CenterDepot = new ChoreoTraj(
        "CenterDepot",
        OptionalInt.empty(),
        3.33012,
        new Pose2d(3.68, 4.0345, Rotation2d.fromRadians(0)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterDepot$0 = new ChoreoTraj(
        "CenterDepot",
        OptionalInt.of(0),
        1.49078,
        new Pose2d(3.68, 4.0345, Rotation2d.fromRadians(0)),
        new Pose2d(1.25, 5.9843, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterDepot$1 = new ChoreoTraj(
        "CenterDepot",
        OptionalInt.of(1),
        0.72281,
        new Pose2d(1.25, 5.9843, Rotation2d.fromRadians(3.14159)),
        new Pose2d(0.59855, 5.9843, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterDepot$2 = new ChoreoTraj(
        "CenterDepot",
        OptionalInt.of(2),
        1.11653,
        new Pose2d(0.59855, 5.9843, Rotation2d.fromRadians(3.14159)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    public static final ChoreoTraj CenterOutpost = new ChoreoTraj(
        "CenterOutpost",
        OptionalInt.empty(),
        3.66147,
        new Pose2d(3.68, 4.0345, Rotation2d.fromRadians(0)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterOutpost$0 = new ChoreoTraj(
        "CenterOutpost",
        OptionalInt.of(0),
        2.34004,
        new Pose2d(3.68, 4.0345, Rotation2d.fromRadians(0)),
        new Pose2d(0.56, 0.68, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterOutpost$1 = new ChoreoTraj(
        "CenterOutpost",
        OptionalInt.of(1),
        1.3214299999999999,
        new Pose2d(0.56, 0.68, Rotation2d.fromRadians(3.14159)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    public static final ChoreoTraj CenterDepotMid = new ChoreoTraj(
        "CenterDepotMid",
        OptionalInt.empty(),
        10.33545,
        new Pose2d(3.68, 4.0345, Rotation2d.fromRadians(0)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterDepotMid$0 = new ChoreoTraj(
        "CenterDepotMid",
        OptionalInt.of(0),
        1.49078,
        new Pose2d(3.68, 4.0345, Rotation2d.fromRadians(0)),
        new Pose2d(1.25, 5.9843, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterDepotMid$1 = new ChoreoTraj(
        "CenterDepotMid",
        OptionalInt.of(1),
        0.72281,
        new Pose2d(1.25, 5.9843, Rotation2d.fromRadians(3.14159)),
        new Pose2d(0.59855, 5.9843, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterDepotMid$2 = new ChoreoTraj(
        "CenterDepotMid",
        OptionalInt.of(2),
        1.11653,
        new Pose2d(0.59855, 5.9843, Rotation2d.fromRadians(3.14159)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterDepotMid$3 = new ChoreoTraj(
        "CenterDepotMid",
        OptionalInt.of(3),
        2.83612,
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674)),
        new Pose2d(8.05, 7.069, Rotation2d.fromRadians(-2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterDepotMid$4 = new ChoreoTraj(
        "CenterDepotMid",
        OptionalInt.of(4),
        1.5069299999999997,
        new Pose2d(8.05, 7.069, Rotation2d.fromRadians(-2.0944)),
        new Pose2d(8.05, 4.869, Rotation2d.fromRadians(-2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterDepotMid$5 = new ChoreoTraj(
        "CenterDepotMid",
        OptionalInt.of(5),
        2.66228,
        new Pose2d(8.05, 4.869, Rotation2d.fromRadians(-2.0944)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    public static final ChoreoTraj CenterOutpostMid = new ChoreoTraj(
        "CenterOutpostMid",
        OptionalInt.empty(),
        10.78612,
        new Pose2d(3.68, 4.0345, Rotation2d.fromRadians(0)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterOutpostMid$0 = new ChoreoTraj(
        "CenterOutpostMid",
        OptionalInt.of(0),
        2.34004,
        new Pose2d(3.68, 4.0345, Rotation2d.fromRadians(0)),
        new Pose2d(0.56, 0.68, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterOutpostMid$1 = new ChoreoTraj(
        "CenterOutpostMid",
        OptionalInt.of(1),
        1.3214299999999999,
        new Pose2d(0.56, 0.68, Rotation2d.fromRadians(3.14159)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterOutpostMid$2 = new ChoreoTraj(
        "CenterOutpostMid",
        OptionalInt.of(2),
        2.8747599999999998,
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265)),
        new Pose2d(8.05, 1, Rotation2d.fromRadians(2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterOutpostMid$3 = new ChoreoTraj(
        "CenterOutpostMid",
        OptionalInt.of(3),
        1.4966299999999997,
        new Pose2d(8.05, 1, Rotation2d.fromRadians(2.0944)),
        new Pose2d(8.05, 3.2, Rotation2d.fromRadians(2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterOutpostMid$4 = new ChoreoTraj(
        "CenterOutpostMid",
        OptionalInt.of(4),
        2.753260000000001,
        new Pose2d(8.05, 3.2, Rotation2d.fromRadians(2.0944)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    public static final ChoreoTraj CenterOutpostFar = new ChoreoTraj(
        "CenterOutpostFar",
        OptionalInt.empty(),
        10.94329,
        new Pose2d(3.68, 4.0345, Rotation2d.fromRadians(0)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterOutpostFar$0 = new ChoreoTraj(
        "CenterOutpostFar",
        OptionalInt.of(0),
        2.34004,
        new Pose2d(3.68, 4.0345, Rotation2d.fromRadians(0)),
        new Pose2d(0.56, 0.68, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterOutpostFar$1 = new ChoreoTraj(
        "CenterOutpostFar",
        OptionalInt.of(1),
        1.3214299999999999,
        new Pose2d(0.56, 0.68, Rotation2d.fromRadians(3.14159)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterOutpostFar$2 = new ChoreoTraj(
        "CenterOutpostFar",
        OptionalInt.of(2),
        3.02985,
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265)),
        new Pose2d(8.75, 1, Rotation2d.fromRadians(2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterOutpostFar$3 = new ChoreoTraj(
        "CenterOutpostFar",
        OptionalInt.of(3),
        1.3583000000000007,
        new Pose2d(8.75, 1, Rotation2d.fromRadians(2.0944)),
        new Pose2d(8.75, 3, Rotation2d.fromRadians(2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterOutpostFar$4 = new ChoreoTraj(
        "CenterOutpostFar",
        OptionalInt.of(4),
        2.8936699999999984,
        new Pose2d(8.75, 3, Rotation2d.fromRadians(2.0944)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    public static final ChoreoTraj CenterDepotFar = new ChoreoTraj(
        "CenterDepotFar",
        OptionalInt.empty(),
        10.50367,
        new Pose2d(3.68, 4.0345, Rotation2d.fromRadians(0)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterDepotFar$0 = new ChoreoTraj(
        "CenterDepotFar",
        OptionalInt.of(0),
        1.49078,
        new Pose2d(3.68, 4.0345, Rotation2d.fromRadians(0)),
        new Pose2d(1.25, 5.9843, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterDepotFar$1 = new ChoreoTraj(
        "CenterDepotFar",
        OptionalInt.of(1),
        0.72281,
        new Pose2d(1.25, 5.9843, Rotation2d.fromRadians(3.14159)),
        new Pose2d(0.59855, 5.9843, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterDepotFar$2 = new ChoreoTraj(
        "CenterDepotFar",
        OptionalInt.of(2),
        1.11653,
        new Pose2d(0.59855, 5.9843, Rotation2d.fromRadians(3.14159)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterDepotFar$3 = new ChoreoTraj(
        "CenterDepotFar",
        OptionalInt.of(3),
        2.9969099999999997,
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674)),
        new Pose2d(8.75, 7.069, Rotation2d.fromRadians(-1.91986))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterDepotFar$4 = new ChoreoTraj(
        "CenterDepotFar",
        OptionalInt.of(4),
        1.3579400000000001,
        new Pose2d(8.75, 7.069, Rotation2d.fromRadians(-1.91986)),
        new Pose2d(8.75, 5.069, Rotation2d.fromRadians(-1.91986))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterDepotFar$5 = new ChoreoTraj(
        "CenterDepotFar",
        OptionalInt.of(5),
        2.8186999999999998,
        new Pose2d(8.75, 5.069, Rotation2d.fromRadians(-1.91986)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    public static final ChoreoTraj CenterDepotClose = new ChoreoTraj(
        "CenterDepotClose",
        OptionalInt.empty(),
        9.19868,
        new Pose2d(3.68, 4.0345, Rotation2d.fromRadians(0)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterDepotClose$0 = new ChoreoTraj(
        "CenterDepotClose",
        OptionalInt.of(0),
        1.49078,
        new Pose2d(3.68, 4.0345, Rotation2d.fromRadians(0)),
        new Pose2d(1.25, 5.9843, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterDepotClose$1 = new ChoreoTraj(
        "CenterDepotClose",
        OptionalInt.of(1),
        0.72281,
        new Pose2d(1.25, 5.9843, Rotation2d.fromRadians(3.14159)),
        new Pose2d(0.59855, 5.9843, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterDepotClose$2 = new ChoreoTraj(
        "CenterDepotClose",
        OptionalInt.of(2),
        1.11653,
        new Pose2d(0.59855, 5.9843, Rotation2d.fromRadians(3.14159)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterDepotClose$3 = new ChoreoTraj(
        "CenterDepotClose",
        OptionalInt.of(3),
        2.2886499999999996,
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674)),
        new Pose2d(6.2, 6.069, Rotation2d.fromRadians(-1.5708))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterDepotClose$4 = new ChoreoTraj(
        "CenterDepotClose",
        OptionalInt.of(4),
        1.1284500000000008,
        new Pose2d(6.2, 6.069, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(6.2, 4.569, Rotation2d.fromRadians(-1.5708))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterDepotClose$5 = new ChoreoTraj(
        "CenterDepotClose",
        OptionalInt.of(5),
        2.451459999999999,
        new Pose2d(6.2, 4.569, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    public static final ChoreoTraj CenterOutpostClose = new ChoreoTraj(
        "CenterOutpostClose",
        OptionalInt.empty(),
        9.5349,
        new Pose2d(3.68, 4.0345, Rotation2d.fromRadians(0)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterOutpostClose$0 = new ChoreoTraj(
        "CenterOutpostClose",
        OptionalInt.of(0),
        2.34004,
        new Pose2d(3.68, 4.0345, Rotation2d.fromRadians(0)),
        new Pose2d(0.56, 0.68, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterOutpostClose$1 = new ChoreoTraj(
        "CenterOutpostClose",
        OptionalInt.of(1),
        1.3214299999999999,
        new Pose2d(0.56, 0.68, Rotation2d.fromRadians(3.14159)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterOutpostClose$2 = new ChoreoTraj(
        "CenterOutpostClose",
        OptionalInt.of(2),
        2.2769600000000003,
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265)),
        new Pose2d(6.2, 2, Rotation2d.fromRadians(1.5708))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterOutpostClose$3 = new ChoreoTraj(
        "CenterOutpostClose",
        OptionalInt.of(3),
        1.1391299999999998,
        new Pose2d(6.2, 2, Rotation2d.fromRadians(1.5708)),
        new Pose2d(6.2, 3.5, Rotation2d.fromRadians(1.5708))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj CenterOutpostClose$4 = new ChoreoTraj(
        "CenterOutpostClose",
        OptionalInt.of(4),
        2.4573400000000003,
        new Pose2d(6.2, 3.5, Rotation2d.fromRadians(1.5708)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    public static final ChoreoTraj FarLeftDepotClose = new ChoreoTraj(
        "FarLeftDepotClose",
        OptionalInt.empty(),
        9.11744,
        new Pose2d(3.68, 7.589, Rotation2d.fromRadians(0)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarLeftDepotClose$0 = new ChoreoTraj(
        "FarLeftDepotClose",
        OptionalInt.of(0),
        1.34033,
        new Pose2d(3.68, 7.589, Rotation2d.fromRadians(0)),
        new Pose2d(1.25, 5.9843, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarLeftDepotClose$1 = new ChoreoTraj(
        "FarLeftDepotClose",
        OptionalInt.of(1),
        0.72265,
        new Pose2d(1.25, 5.9843, Rotation2d.fromRadians(3.14159)),
        new Pose2d(0.59855, 5.9843, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarLeftDepotClose$2 = new ChoreoTraj(
        "FarLeftDepotClose",
        OptionalInt.of(2),
        1.11653,
        new Pose2d(0.59855, 5.9843, Rotation2d.fromRadians(3.14159)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarLeftDepotClose$3 = new ChoreoTraj(
        "FarLeftDepotClose",
        OptionalInt.of(3),
        2.34918,
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674)),
        new Pose2d(6.2, 6.069, Rotation2d.fromRadians(-1.5708))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarLeftDepotClose$4 = new ChoreoTraj(
        "FarLeftDepotClose",
        OptionalInt.of(4),
        1.1385899999999998,
        new Pose2d(6.2, 6.069, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(6.2, 4.569, Rotation2d.fromRadians(-1.5708))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarLeftDepotClose$5 = new ChoreoTraj(
        "FarLeftDepotClose",
        OptionalInt.of(5),
        2.4501600000000003,
        new Pose2d(6.2, 4.569, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    public static final ChoreoTraj FarLeftDepotMid = new ChoreoTraj(
        "FarLeftDepotMid",
        OptionalInt.empty(),
        10.18484,
        new Pose2d(3.68, 7.589, Rotation2d.fromRadians(0)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarLeftDepotMid$0 = new ChoreoTraj(
        "FarLeftDepotMid",
        OptionalInt.of(0),
        1.34033,
        new Pose2d(3.68, 7.589, Rotation2d.fromRadians(0)),
        new Pose2d(1.25, 5.9843, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarLeftDepotMid$1 = new ChoreoTraj(
        "FarLeftDepotMid",
        OptionalInt.of(1),
        0.72265,
        new Pose2d(1.25, 5.9843, Rotation2d.fromRadians(3.14159)),
        new Pose2d(0.59855, 5.9843, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarLeftDepotMid$2 = new ChoreoTraj(
        "FarLeftDepotMid",
        OptionalInt.of(2),
        1.11653,
        new Pose2d(0.59855, 5.9843, Rotation2d.fromRadians(3.14159)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarLeftDepotMid$3 = new ChoreoTraj(
        "FarLeftDepotMid",
        OptionalInt.of(3),
        2.8361199999999998,
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674)),
        new Pose2d(8.05, 7.069, Rotation2d.fromRadians(-2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarLeftDepotMid$4 = new ChoreoTraj(
        "FarLeftDepotMid",
        OptionalInt.of(4),
        1.5069300000000005,
        new Pose2d(8.05, 7.069, Rotation2d.fromRadians(-2.0944)),
        new Pose2d(8.05, 4.869, Rotation2d.fromRadians(-2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarLeftDepotMid$5 = new ChoreoTraj(
        "FarLeftDepotMid",
        OptionalInt.of(5),
        2.662279999999999,
        new Pose2d(8.05, 4.869, Rotation2d.fromRadians(-2.0944)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    public static final ChoreoTraj FarLeftDepotFar = new ChoreoTraj(
        "FarLeftDepotFar",
        OptionalInt.empty(),
        10.35306,
        new Pose2d(3.68, 7.589, Rotation2d.fromRadians(0)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarLeftDepotFar$0 = new ChoreoTraj(
        "FarLeftDepotFar",
        OptionalInt.of(0),
        1.34033,
        new Pose2d(3.68, 7.589, Rotation2d.fromRadians(0)),
        new Pose2d(1.25, 5.9843, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarLeftDepotFar$1 = new ChoreoTraj(
        "FarLeftDepotFar",
        OptionalInt.of(1),
        0.72265,
        new Pose2d(1.25, 5.9843, Rotation2d.fromRadians(3.14159)),
        new Pose2d(0.59855, 5.9843, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarLeftDepotFar$2 = new ChoreoTraj(
        "FarLeftDepotFar",
        OptionalInt.of(2),
        1.11653,
        new Pose2d(0.59855, 5.9843, Rotation2d.fromRadians(3.14159)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarLeftDepotFar$3 = new ChoreoTraj(
        "FarLeftDepotFar",
        OptionalInt.of(3),
        2.99691,
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674)),
        new Pose2d(8.75, 7.069, Rotation2d.fromRadians(-1.91986))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarLeftDepotFar$4 = new ChoreoTraj(
        "FarLeftDepotFar",
        OptionalInt.of(4),
        1.3579400000000001,
        new Pose2d(8.75, 7.069, Rotation2d.fromRadians(-1.91986)),
        new Pose2d(8.75, 5.069, Rotation2d.fromRadians(-1.91986))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarLeftDepotFar$5 = new ChoreoTraj(
        "FarLeftDepotFar",
        OptionalInt.of(5),
        2.818699999999999,
        new Pose2d(8.75, 5.069, Rotation2d.fromRadians(-1.91986)),
        new Pose2d(2.527, 5.121, Rotation2d.fromRadians(-2.11674))
    );
    public static final ChoreoTraj FarRightOutpostClose = new ChoreoTraj(
        "FarRightOutpostClose",
        OptionalInt.empty(),
        8.98607,
        new Pose2d(3.68, 0.48, Rotation2d.fromRadians(0)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarRightOutpostClose$0 = new ChoreoTraj(
        "FarRightOutpostClose",
        OptionalInt.of(0),
        1.79121,
        new Pose2d(3.68, 0.48, Rotation2d.fromRadians(0)),
        new Pose2d(0.56, 0.68, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarRightOutpostClose$1 = new ChoreoTraj(
        "FarRightOutpostClose",
        OptionalInt.of(1),
        1.3214299999999999,
        new Pose2d(0.56, 0.68, Rotation2d.fromRadians(3.14159)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarRightOutpostClose$2 = new ChoreoTraj(
        "FarRightOutpostClose",
        OptionalInt.of(2),
        2.27696,
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265)),
        new Pose2d(6.2, 2, Rotation2d.fromRadians(1.5708))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarRightOutpostClose$3 = new ChoreoTraj(
        "FarRightOutpostClose",
        OptionalInt.of(3),
        1.1391300000000006,
        new Pose2d(6.2, 2, Rotation2d.fromRadians(1.5708)),
        new Pose2d(6.2, 3.5, Rotation2d.fromRadians(1.5708))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarRightOutpostClose$4 = new ChoreoTraj(
        "FarRightOutpostClose",
        OptionalInt.of(4),
        2.4573399999999994,
        new Pose2d(6.2, 3.5, Rotation2d.fromRadians(1.5708)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    public static final ChoreoTraj FarRightOutpostMid = new ChoreoTraj(
        "FarRightOutpostMid",
        OptionalInt.empty(),
        10.23729,
        new Pose2d(3.68, 0.48, Rotation2d.fromRadians(0)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarRightOutpostMid$0 = new ChoreoTraj(
        "FarRightOutpostMid",
        OptionalInt.of(0),
        1.79121,
        new Pose2d(3.68, 0.48, Rotation2d.fromRadians(0)),
        new Pose2d(0.56, 0.68, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarRightOutpostMid$1 = new ChoreoTraj(
        "FarRightOutpostMid",
        OptionalInt.of(1),
        1.3214299999999999,
        new Pose2d(0.56, 0.68, Rotation2d.fromRadians(3.14159)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarRightOutpostMid$2 = new ChoreoTraj(
        "FarRightOutpostMid",
        OptionalInt.of(2),
        2.87476,
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265)),
        new Pose2d(8.05, 1, Rotation2d.fromRadians(2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarRightOutpostMid$3 = new ChoreoTraj(
        "FarRightOutpostMid",
        OptionalInt.of(3),
        1.4966299999999997,
        new Pose2d(8.05, 1, Rotation2d.fromRadians(2.0944)),
        new Pose2d(8.05, 3.2, Rotation2d.fromRadians(2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarRightOutpostMid$4 = new ChoreoTraj(
        "FarRightOutpostMid",
        OptionalInt.of(4),
        2.75326,
        new Pose2d(8.05, 3.2, Rotation2d.fromRadians(2.0944)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    public static final ChoreoTraj FarRightOutpostFar = new ChoreoTraj(
        "FarRightOutpostFar",
        OptionalInt.empty(),
        10.39446,
        new Pose2d(3.68, 0.48, Rotation2d.fromRadians(0)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarRightOutpostFar$0 = new ChoreoTraj(
        "FarRightOutpostFar",
        OptionalInt.of(0),
        1.79121,
        new Pose2d(3.68, 0.48, Rotation2d.fromRadians(0)),
        new Pose2d(0.56, 0.68, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarRightOutpostFar$1 = new ChoreoTraj(
        "FarRightOutpostFar",
        OptionalInt.of(1),
        1.3214299999999999,
        new Pose2d(0.56, 0.68, Rotation2d.fromRadians(3.14159)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarRightOutpostFar$2 = new ChoreoTraj(
        "FarRightOutpostFar",
        OptionalInt.of(2),
        3.0298499999999997,
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265)),
        new Pose2d(8.75, 1, Rotation2d.fromRadians(2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarRightOutpostFar$3 = new ChoreoTraj(
        "FarRightOutpostFar",
        OptionalInt.of(3),
        1.3583000000000007,
        new Pose2d(8.75, 1, Rotation2d.fromRadians(2.0944)),
        new Pose2d(8.75, 3, Rotation2d.fromRadians(2.0944))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj FarRightOutpostFar$4 = new ChoreoTraj(
        "FarRightOutpostFar",
        OptionalInt.of(4),
        2.89367,
        new Pose2d(8.75, 3, Rotation2d.fromRadians(2.0944)),
        new Pose2d(2.424, 2.776, Rotation2d.fromRadians(-1.11265))
    );

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
        Map.entry("FarLeftDepot", FarLeftDepot),
        Map.entry("FarLeftDepot$0", FarLeftDepot$0),
        Map.entry("FarLeftDepot$1", FarLeftDepot$1),
        Map.entry("FarLeftDepot$2", FarLeftDepot$2),
        Map.entry("FarRightOutpost", FarRightOutpost),
        Map.entry("FarRightOutpost$0", FarRightOutpost$0),
        Map.entry("FarRightOutpost$1", FarRightOutpost$1),
        Map.entry("LeftBumpClose", LeftBumpClose),
        Map.entry("LeftBumpClose$0", LeftBumpClose$0),
        Map.entry("LeftBumpClose$1", LeftBumpClose$1),
        Map.entry("LeftBumpClose$2", LeftBumpClose$2),
        Map.entry("LeftBumpFar", LeftBumpFar),
        Map.entry("LeftBumpFar$0", LeftBumpFar$0),
        Map.entry("LeftBumpFar$1", LeftBumpFar$1),
        Map.entry("LeftBumpFar$2", LeftBumpFar$2),
        Map.entry("LeftBumpFarAcross", LeftBumpFarAcross),
        Map.entry("LeftBumpFarAcross$0", LeftBumpFarAcross$0),
        Map.entry("LeftBumpFarAcross$1", LeftBumpFarAcross$1),
        Map.entry("LeftBumpFarAcross$2", LeftBumpFarAcross$2),
        Map.entry("LeftBumpFarAcrossClose", LeftBumpFarAcrossClose),
        Map.entry("LeftBumpFarAcrossClose$0", LeftBumpFarAcrossClose$0),
        Map.entry("LeftBumpFarAcrossClose$1", LeftBumpFarAcrossClose$1),
        Map.entry("LeftBumpFarAcrossClose$2", LeftBumpFarAcrossClose$2),
        Map.entry("LeftBumpFarAcrossClose$3", LeftBumpFarAcrossClose$3),
        Map.entry("LeftBumpFarAcrossClose$4", LeftBumpFarAcrossClose$4),
        Map.entry("LeftBumpFarAcrossClose$5", LeftBumpFarAcrossClose$5),
        Map.entry("LeftBumpFarAcrossOutpost", LeftBumpFarAcrossOutpost),
        Map.entry("LeftBumpFarAcrossOutpost$0", LeftBumpFarAcrossOutpost$0),
        Map.entry("LeftBumpFarAcrossOutpost$1", LeftBumpFarAcrossOutpost$1),
        Map.entry("LeftBumpFarAcrossOutpost$2", LeftBumpFarAcrossOutpost$2),
        Map.entry("LeftBumpFarAcrossOutpost$3", LeftBumpFarAcrossOutpost$3),
        Map.entry("LeftBumpFarAcrossOutpost$4", LeftBumpFarAcrossOutpost$4),
        Map.entry("LeftBumpFarClose", LeftBumpFarClose),
        Map.entry("LeftBumpFarClose$0", LeftBumpFarClose$0),
        Map.entry("LeftBumpFarClose$1", LeftBumpFarClose$1),
        Map.entry("LeftBumpFarClose$2", LeftBumpFarClose$2),
        Map.entry("LeftBumpFarClose$3", LeftBumpFarClose$3),
        Map.entry("LeftBumpFarClose$4", LeftBumpFarClose$4),
        Map.entry("LeftBumpFarClose$5", LeftBumpFarClose$5),
        Map.entry("LeftBumpFarDepot", LeftBumpFarDepot),
        Map.entry("LeftBumpFarDepot$0", LeftBumpFarDepot$0),
        Map.entry("LeftBumpFarDepot$1", LeftBumpFarDepot$1),
        Map.entry("LeftBumpFarDepot$2", LeftBumpFarDepot$2),
        Map.entry("LeftBumpFarDepot$3", LeftBumpFarDepot$3),
        Map.entry("LeftBumpFarDepot$4", LeftBumpFarDepot$4),
        Map.entry("LeftBumpFarDepot$5", LeftBumpFarDepot$5),
        Map.entry("LeftBumpMid", LeftBumpMid),
        Map.entry("LeftBumpMid$0", LeftBumpMid$0),
        Map.entry("LeftBumpMid$1", LeftBumpMid$1),
        Map.entry("LeftBumpMid$2", LeftBumpMid$2),
        Map.entry("LeftBumpMidClose", LeftBumpMidClose),
        Map.entry("LeftBumpMidClose$0", LeftBumpMidClose$0),
        Map.entry("LeftBumpMidClose$1", LeftBumpMidClose$1),
        Map.entry("LeftBumpMidClose$2", LeftBumpMidClose$2),
        Map.entry("LeftBumpMidClose$3", LeftBumpMidClose$3),
        Map.entry("LeftBumpMidClose$4", LeftBumpMidClose$4),
        Map.entry("LeftBumpMidClose$5", LeftBumpMidClose$5),
        Map.entry("LeftBumpMidDepot", LeftBumpMidDepot),
        Map.entry("LeftBumpMidDepot$0", LeftBumpMidDepot$0),
        Map.entry("LeftBumpMidDepot$1", LeftBumpMidDepot$1),
        Map.entry("LeftBumpMidDepot$2", LeftBumpMidDepot$2),
        Map.entry("LeftBumpMidDepot$3", LeftBumpMidDepot$3),
        Map.entry("LeftBumpMidDepot$4", LeftBumpMidDepot$4),
        Map.entry("LeftBumpMidDepot$5", LeftBumpMidDepot$5),
        Map.entry("RightBumpClose", RightBumpClose),
        Map.entry("RightBumpClose$0", RightBumpClose$0),
        Map.entry("RightBumpClose$1", RightBumpClose$1),
        Map.entry("RightBumpClose$2", RightBumpClose$2),
        Map.entry("RightBumpFar", RightBumpFar),
        Map.entry("RightBumpFar$0", RightBumpFar$0),
        Map.entry("RightBumpFar$1", RightBumpFar$1),
        Map.entry("RightBumpFar$2", RightBumpFar$2),
        Map.entry("RightBumpFarAcross", RightBumpFarAcross),
        Map.entry("RightBumpFarAcross$0", RightBumpFarAcross$0),
        Map.entry("RightBumpFarAcross$1", RightBumpFarAcross$1),
        Map.entry("RightBumpFarAcross$2", RightBumpFarAcross$2),
        Map.entry("RightBumpFarAcrossClose", RightBumpFarAcrossClose),
        Map.entry("RightBumpFarAcrossClose$0", RightBumpFarAcrossClose$0),
        Map.entry("RightBumpFarAcrossClose$1", RightBumpFarAcrossClose$1),
        Map.entry("RightBumpFarAcrossClose$2", RightBumpFarAcrossClose$2),
        Map.entry("RightBumpFarAcrossClose$3", RightBumpFarAcrossClose$3),
        Map.entry("RightBumpFarAcrossClose$4", RightBumpFarAcrossClose$4),
        Map.entry("RightBumpFarAcrossClose$5", RightBumpFarAcrossClose$5),
        Map.entry("RightBumpFarAcrossDepot", RightBumpFarAcrossDepot),
        Map.entry("RightBumpFarAcrossDepot$0", RightBumpFarAcrossDepot$0),
        Map.entry("RightBumpFarAcrossDepot$1", RightBumpFarAcrossDepot$1),
        Map.entry("RightBumpFarAcrossDepot$2", RightBumpFarAcrossDepot$2),
        Map.entry("RightBumpFarAcrossDepot$3", RightBumpFarAcrossDepot$3),
        Map.entry("RightBumpFarAcrossDepot$4", RightBumpFarAcrossDepot$4),
        Map.entry("RightBumpFarAcrossDepot$5", RightBumpFarAcrossDepot$5),
        Map.entry("RightBumpFarClose", RightBumpFarClose),
        Map.entry("RightBumpFarClose$0", RightBumpFarClose$0),
        Map.entry("RightBumpFarClose$1", RightBumpFarClose$1),
        Map.entry("RightBumpFarClose$2", RightBumpFarClose$2),
        Map.entry("RightBumpFarClose$3", RightBumpFarClose$3),
        Map.entry("RightBumpFarClose$4", RightBumpFarClose$4),
        Map.entry("RightBumpFarClose$5", RightBumpFarClose$5),
        Map.entry("RightBumpFarOutpost", RightBumpFarOutpost),
        Map.entry("RightBumpFarOutpost$0", RightBumpFarOutpost$0),
        Map.entry("RightBumpFarOutpost$1", RightBumpFarOutpost$1),
        Map.entry("RightBumpFarOutpost$2", RightBumpFarOutpost$2),
        Map.entry("RightBumpFarOutpost$3", RightBumpFarOutpost$3),
        Map.entry("RightBumpFarOutpost$4", RightBumpFarOutpost$4),
        Map.entry("RightBumpMid", RightBumpMid),
        Map.entry("RightBumpMid$0", RightBumpMid$0),
        Map.entry("RightBumpMid$1", RightBumpMid$1),
        Map.entry("RightBumpMid$2", RightBumpMid$2),
        Map.entry("RightBumpMidClose", RightBumpMidClose),
        Map.entry("RightBumpMidClose$0", RightBumpMidClose$0),
        Map.entry("RightBumpMidClose$1", RightBumpMidClose$1),
        Map.entry("RightBumpMidClose$2", RightBumpMidClose$2),
        Map.entry("RightBumpMidClose$3", RightBumpMidClose$3),
        Map.entry("RightBumpMidClose$4", RightBumpMidClose$4),
        Map.entry("RightBumpMidClose$5", RightBumpMidClose$5),
        Map.entry("RightBumpMidOutpost", RightBumpMidOutpost),
        Map.entry("RightBumpMidOutpost$0", RightBumpMidOutpost$0),
        Map.entry("RightBumpMidOutpost$1", RightBumpMidOutpost$1),
        Map.entry("RightBumpMidOutpost$2", RightBumpMidOutpost$2),
        Map.entry("RightBumpMidOutpost$3", RightBumpMidOutpost$3),
        Map.entry("RightBumpMidOutpost$4", RightBumpMidOutpost$4),
        Map.entry("Warmup", Warmup),
        Map.entry("Center", Center),
        Map.entry("CenterDepot", CenterDepot),
        Map.entry("CenterDepot$0", CenterDepot$0),
        Map.entry("CenterDepot$1", CenterDepot$1),
        Map.entry("CenterDepot$2", CenterDepot$2),
        Map.entry("CenterOutpost", CenterOutpost),
        Map.entry("CenterOutpost$0", CenterOutpost$0),
        Map.entry("CenterOutpost$1", CenterOutpost$1),
        Map.entry("CenterDepotMid", CenterDepotMid),
        Map.entry("CenterDepotMid$0", CenterDepotMid$0),
        Map.entry("CenterDepotMid$1", CenterDepotMid$1),
        Map.entry("CenterDepotMid$2", CenterDepotMid$2),
        Map.entry("CenterDepotMid$3", CenterDepotMid$3),
        Map.entry("CenterDepotMid$4", CenterDepotMid$4),
        Map.entry("CenterDepotMid$5", CenterDepotMid$5),
        Map.entry("CenterOutpostMid", CenterOutpostMid),
        Map.entry("CenterOutpostMid$0", CenterOutpostMid$0),
        Map.entry("CenterOutpostMid$1", CenterOutpostMid$1),
        Map.entry("CenterOutpostMid$2", CenterOutpostMid$2),
        Map.entry("CenterOutpostMid$3", CenterOutpostMid$3),
        Map.entry("CenterOutpostMid$4", CenterOutpostMid$4),
        Map.entry("CenterOutpostFar", CenterOutpostFar),
        Map.entry("CenterOutpostFar$0", CenterOutpostFar$0),
        Map.entry("CenterOutpostFar$1", CenterOutpostFar$1),
        Map.entry("CenterOutpostFar$2", CenterOutpostFar$2),
        Map.entry("CenterOutpostFar$3", CenterOutpostFar$3),
        Map.entry("CenterOutpostFar$4", CenterOutpostFar$4),
        Map.entry("CenterDepotFar", CenterDepotFar),
        Map.entry("CenterDepotFar$0", CenterDepotFar$0),
        Map.entry("CenterDepotFar$1", CenterDepotFar$1),
        Map.entry("CenterDepotFar$2", CenterDepotFar$2),
        Map.entry("CenterDepotFar$3", CenterDepotFar$3),
        Map.entry("CenterDepotFar$4", CenterDepotFar$4),
        Map.entry("CenterDepotFar$5", CenterDepotFar$5),
        Map.entry("CenterDepotClose", CenterDepotClose),
        Map.entry("CenterDepotClose$0", CenterDepotClose$0),
        Map.entry("CenterDepotClose$1", CenterDepotClose$1),
        Map.entry("CenterDepotClose$2", CenterDepotClose$2),
        Map.entry("CenterDepotClose$3", CenterDepotClose$3),
        Map.entry("CenterDepotClose$4", CenterDepotClose$4),
        Map.entry("CenterDepotClose$5", CenterDepotClose$5),
        Map.entry("CenterOutpostClose", CenterOutpostClose),
        Map.entry("CenterOutpostClose$0", CenterOutpostClose$0),
        Map.entry("CenterOutpostClose$1", CenterOutpostClose$1),
        Map.entry("CenterOutpostClose$2", CenterOutpostClose$2),
        Map.entry("CenterOutpostClose$3", CenterOutpostClose$3),
        Map.entry("CenterOutpostClose$4", CenterOutpostClose$4),
        Map.entry("FarLeftDepotClose", FarLeftDepotClose),
        Map.entry("FarLeftDepotClose$0", FarLeftDepotClose$0),
        Map.entry("FarLeftDepotClose$1", FarLeftDepotClose$1),
        Map.entry("FarLeftDepotClose$2", FarLeftDepotClose$2),
        Map.entry("FarLeftDepotClose$3", FarLeftDepotClose$3),
        Map.entry("FarLeftDepotClose$4", FarLeftDepotClose$4),
        Map.entry("FarLeftDepotClose$5", FarLeftDepotClose$5),
        Map.entry("FarLeftDepotMid", FarLeftDepotMid),
        Map.entry("FarLeftDepotMid$0", FarLeftDepotMid$0),
        Map.entry("FarLeftDepotMid$1", FarLeftDepotMid$1),
        Map.entry("FarLeftDepotMid$2", FarLeftDepotMid$2),
        Map.entry("FarLeftDepotMid$3", FarLeftDepotMid$3),
        Map.entry("FarLeftDepotMid$4", FarLeftDepotMid$4),
        Map.entry("FarLeftDepotMid$5", FarLeftDepotMid$5),
        Map.entry("FarLeftDepotFar", FarLeftDepotFar),
        Map.entry("FarLeftDepotFar$0", FarLeftDepotFar$0),
        Map.entry("FarLeftDepotFar$1", FarLeftDepotFar$1),
        Map.entry("FarLeftDepotFar$2", FarLeftDepotFar$2),
        Map.entry("FarLeftDepotFar$3", FarLeftDepotFar$3),
        Map.entry("FarLeftDepotFar$4", FarLeftDepotFar$4),
        Map.entry("FarLeftDepotFar$5", FarLeftDepotFar$5),
        Map.entry("FarRightOutpostClose", FarRightOutpostClose),
        Map.entry("FarRightOutpostClose$0", FarRightOutpostClose$0),
        Map.entry("FarRightOutpostClose$1", FarRightOutpostClose$1),
        Map.entry("FarRightOutpostClose$2", FarRightOutpostClose$2),
        Map.entry("FarRightOutpostClose$3", FarRightOutpostClose$3),
        Map.entry("FarRightOutpostClose$4", FarRightOutpostClose$4),
        Map.entry("FarRightOutpostMid", FarRightOutpostMid),
        Map.entry("FarRightOutpostMid$0", FarRightOutpostMid$0),
        Map.entry("FarRightOutpostMid$1", FarRightOutpostMid$1),
        Map.entry("FarRightOutpostMid$2", FarRightOutpostMid$2),
        Map.entry("FarRightOutpostMid$3", FarRightOutpostMid$3),
        Map.entry("FarRightOutpostMid$4", FarRightOutpostMid$4),
        Map.entry("FarRightOutpostFar", FarRightOutpostFar),
        Map.entry("FarRightOutpostFar$0", FarRightOutpostFar$0),
        Map.entry("FarRightOutpostFar$1", FarRightOutpostFar$1),
        Map.entry("FarRightOutpostFar$2", FarRightOutpostFar$2),
        Map.entry("FarRightOutpostFar$3", FarRightOutpostFar$3),
        Map.entry("FarRightOutpostFar$4", FarRightOutpostFar$4)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
// spotless:on
