// Copyright (c) 2026 FRC 167
// https://github.com/icrobotics-team167
//
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file at
// the root directory of this project.

package choreo.util;

/** Internal autogenerated class for storing the current trajectory schema version. */
public class TrajSchemaVersion {
  /** The current trajectory schema version. */
  public static final int TRAJ_SCHEMA_VERSION = 3;

  /** Utility class. */
  private TrajSchemaVersion() {}
}
